load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "agent_settings_pb2",
    srcs = ["agent_settings_pb2.py"],
    pyi_srcs = ["agent_settings_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "artifact_pb2",
    srcs = ["artifact_pb2.py"],
    pyi_srcs = ["artifact_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//agent_v2:agent_pb2",
        "//agent_v3/genai/proto/integrations:integrations_pb2",
        "@pip//protobuf",
    ],
)

py_library(
    name = "asr_pb2",
    srcs = ["asr_pb2.py"],
    pyi_srcs = ["asr_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "asr_settings_pb2",
    srcs = ["asr_settings_pb2.py"],
    pyi_srcs = ["asr_settings_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "bundle_pb2",
    srcs = ["bundle_pb2.py"],
    pyi_srcs = ["bundle_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":snapshot_pb2",
        "@pip//protobuf",
    ],
)

py_library(
    name = "commands_pb2",
    srcs = ["commands_pb2.py"],
    pyi_srcs = ["commands_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":agent_settings_pb2",
        ":api_integrations_pb2",
        ":asr_settings_pb2",
        ":channels_pb2",
        ":content_filter_settings_pb2",
        ":csat_pb2",
        ":documents_pb2",
        ":end_function_pb2",
        ":entities_pb2",
        ":experimental_config_pb2",
        ":flows_pb2",
        ":functions_pb2",
        ":guardrails_pb2",
        ":handoff_pb2",
        ":integrations_pb2",
        ":keyphrase_boosting_pb2",
        ":knowledge_base_pb2",
        ":languages_pb2",
        ":llm_settings_pb2",
        ":pronunciations_pb2",
        ":sms_pb2",
        ":start_function_pb2",
        ":stop_keywords_pb2",
        ":testing_pb2",
        ":transcript_corrections_pb2",
        ":translations_pb2",
        ":variables_pb2",
        ":variant_pb2",
        ":voice_pb2",
        ":webchat_csat_pb2",
        "@pip//protobuf",
    ],
)

py_library(
    name = "content_filter_settings_pb2",
    srcs = ["content_filter_settings_pb2.py"],
    pyi_srcs = ["content_filter_settings_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "end_function_pb2",
    srcs = ["end_function_pb2.py"],
    pyi_srcs = ["end_function_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":functions_pb2",
        "@pip//protobuf",
    ],
)

py_library(
    name = "experimental_config_pb2",
    srcs = ["experimental_config_pb2.py"],
    pyi_srcs = ["experimental_config_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "flows_pb2",
    srcs = ["flows_pb2.py"],
    pyi_srcs = ["flows_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":entities_pb2",
        ":functions_pb2",
        ":handoff_pb2",
        ":sms_pb2",
        ":variant_pb2",
        "@pip//protobuf",
    ],
)

py_library(
    name = "functions_pb2",
    srcs = ["functions_pb2.py"],
    pyi_srcs = ["functions_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "handoff_pb2",
    srcs = ["handoff_pb2.py"],
    pyi_srcs = ["handoff_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "keyphrase_boosting_pb2",
    srcs = ["keyphrase_boosting_pb2.py"],
    pyi_srcs = ["keyphrase_boosting_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "knowledge_base_pb2",
    srcs = ["knowledge_base_pb2.py"],
    pyi_srcs = ["knowledge_base_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "llm_settings_pb2",
    srcs = ["llm_settings_pb2.py"],
    pyi_srcs = ["llm_settings_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "pronunciations_pb2",
    srcs = ["pronunciations_pb2.py"],
    pyi_srcs = ["pronunciations_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "sms_pb2",
    srcs = ["sms_pb2.py"],
    pyi_srcs = ["sms_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "snapshot_pb2",
    srcs = ["snapshot_pb2.py"],
    pyi_srcs = ["snapshot_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":agent_settings_pb2",
        ":api_integrations_pb2",
        ":asr_pb2",
        ":asr_settings_pb2",
        ":channels_pb2",
        ":child_overwrites_pb2",
        ":content_filter_settings_pb2",
        ":csat_pb2",
        ":documents_pb2",
        ":end_function_pb2",
        ":entities_pb2",
        ":experimental_config_pb2",
        ":flows_pb2",
        ":functions_pb2",
        ":guardrails_pb2",
        ":handoff_pb2",
        ":integrations_pb2",
        ":keyphrase_boosting_pb2",
        ":knowledge_base_pb2",
        ":languages_pb2",
        ":llm_settings_pb2",
        ":pronunciations_pb2",
        ":sms_pb2",
        ":start_function_pb2",
        ":stop_keywords_pb2",
        ":testing_pb2",
        ":transcript_corrections_pb2",
        ":translations_pb2",
        ":variables_pb2",
        ":variant_pb2",
        ":voice_pb2",
        ":webchat_csat_pb2",
        "@pip//protobuf",
    ],
)

py_library(
    name = "start_function_pb2",
    srcs = ["start_function_pb2.py"],
    pyi_srcs = ["start_function_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":functions_pb2",
        "@pip//protobuf",
    ],
)

py_library(
    name = "stop_keywords_pb2",
    srcs = ["stop_keywords_pb2.py"],
    pyi_srcs = ["stop_keywords_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "transcript_corrections_pb2",
    srcs = ["transcript_corrections_pb2.py"],
    pyi_srcs = ["transcript_corrections_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "tts_settings_pb2",
    srcs = ["tts_settings_pb2.py"],
    pyi_srcs = ["tts_settings_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "variant_pb2",
    srcs = ["variant_pb2.py"],
    pyi_srcs = ["variant_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "voice_pb2",
    srcs = ["voice_pb2.py"],
    pyi_srcs = ["voice_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "entities_pb2",
    srcs = ["entities_pb2.py"],
    pyi_srcs = ["entities_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "api_integrations_pb2",
    srcs = ["api_integrations_pb2.py"],
    pyi_srcs = ["api_integrations_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "languages_pb2",
    srcs = ["languages_pb2.py"],
    pyi_srcs = ["languages_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "variables_pb2",
    srcs = ["variables_pb2.py"],
    pyi_srcs = ["variables_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "channels_pb2",
    srcs = ["channels_pb2.py"],
    pyi_srcs = ["channels_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":agent_settings_pb2",
        ":asr_pb2",
        ":asr_settings_pb2",
        ":content_filter_settings_pb2",
        ":llm_settings_pb2",
        "@pip//protobuf",
    ],
)

py_library(
    name = "csat_pb2",
    srcs = ["csat_pb2.py"],
    pyi_srcs = ["csat_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "translations_pb2",
    srcs = ["translations_pb2.py"],
    pyi_srcs = ["translations_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "integrations_pb2",
    srcs = ["integrations_pb2.py"],
    pyi_srcs = ["integrations_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "guardrails_pb2",
    srcs = ["guardrails_pb2.py"],
    pyi_srcs = ["guardrails_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "testing_pb2",
    srcs = ["testing_pb2.py"],
    pyi_srcs = ["testing_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "child_overwrites_pb2",
    srcs = ["child_overwrites_pb2.py"],
    pyi_srcs = ["child_overwrites_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":knowledge_base_pb2",
        "@pip//protobuf",
    ],
)

py_library(
    name = "documents_pb2",
    srcs = ["documents_pb2.py"],
    pyi_srcs = ["documents_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)

py_library(
    name = "webchat_csat_pb2",
    srcs = ["webchat_csat_pb2.py"],
    pyi_srcs = ["webchat_csat_pb2.pyi"],
    visibility = ["//:__subpackages__"],
    deps = ["@pip//protobuf"],
)
