# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: child_overwrites.proto
# Protobuf Python Version: 4.25.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from poly.handlers.protobuf import knowledge_base_pb2 as knowledge__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63hild_overwrites.proto\x12\x10\x63hild_overwrites\x1a\x14knowledge_base.proto\"H\n\x0f\x43hildOverwrites\x12\x35\n\x0eknowledge_base\x18\x01 \x01(\x0b\x32\x1d.knowledge_base.KnowledgeBaseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'child_overwrites_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHILDOVERWRITES']._serialized_start=66
  _globals['_CHILDOVERWRITES']._serialized_end=138
# @@protoc_insertion_point(module_scope)
