# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: documents.proto
# Protobuf Python Version: 4.25.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64ocuments.proto\x12\tdocuments\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n\x08\x44ocument\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\ncreated_by\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nupdated_by\x18\x05 \x01(\t\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"3\n\tDocuments\x12&\n\tdocuments\x18\x01 \x03(\x0b\x32\x13.documents.Document\"0\n\x0f\x44ocument_Create\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"0\n\x0f\x44ocument_Update\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1f\n\x0f\x44ocument_Delete\x12\x0c\n\x04path\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'documents_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOCUMENT']._serialized_start=64
  _globals['_DOCUMENT']._serialized_end=241
  _globals['_DOCUMENTS']._serialized_start=243
  _globals['_DOCUMENTS']._serialized_end=294
  _globals['_DOCUMENT_CREATE']._serialized_start=296
  _globals['_DOCUMENT_CREATE']._serialized_end=344
  _globals['_DOCUMENT_UPDATE']._serialized_start=346
  _globals['_DOCUMENT_UPDATE']._serialized_end=394
  _globals['_DOCUMENT_DELETE']._serialized_start=396
  _globals['_DOCUMENT_DELETE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
