# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm_settings.proto
# Protobuf Python Version: 4.25.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12llm_settings.proto\x12\x0cllm_settings\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n\x0bLLMSettings\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x17\n\nupdated_by\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x33\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x42\r\n\x0b_updated_byB\r\n\x0b_updated_at\"1\n\x1dLLMSettings_UpdateLLMSettings\x12\x10\n\x08model_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_settings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LLMSETTINGS']._serialized_start=70
  _globals['_LLMSETTINGS']._serialized_end=209
  _globals['_LLMSETTINGS_UPDATELLMSETTINGS']._serialized_start=211
  _globals['_LLMSETTINGS_UPDATELLMSETTINGS']._serialized_end=260
# @@protoc_insertion_point(module_scope)
