"""Generation of the local ``_gen`` package of importable type stubs.

The committed modules in ``poly.types`` are already runtime-safe ``.py``
files (generated by ``scripts/sync_runtime_stubs.py``); ``save_imports``
copies them verbatim and adds the two files that are genuinely per-project:
the aggregated ``__init__.py`` and ``decorators.py``.

Copyright PolyAI Limited
"""

import ast
import importlib.resources
import os
from importlib.resources.abc import Traversable

_TYPES_PACKAGE = "poly.types"

# Header for the files save_imports itself generates (__init__.py); copied
# stub modules carry their own committed header.
_GEN_FILE_HEADER = "# flake8: noqa\n# ruff: noqa\n# type: ignore\n# <AUTO GENERATED>\n"


def _read_all_from_stub(source: str) -> list[str] | None:
    """Return the names listed in __all__ of a type source string, or None."""
    tree = ast.parse(source)
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    if isinstance(node.value, (ast.List, ast.Tuple)):
                        return [
                            elt.value
                            for elt in node.value.elts
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
                        ]
    return None


def _load_file_class_maps() -> dict[str, list[str]]:
    """Discover exported names by reading __all__ from each type module.

    Returns:
        A dictionary mapping filenames (e.g. "conversation.py") to the list of
        names declared in that module's __all__.
    """
    result: dict[str, list[str]] = {}
    pkg = importlib.resources.files(_TYPES_PACKAGE)
    for resource in sorted(pkg.iterdir(), key=lambda r: r.name):
        name = resource.name
        if not name.endswith(".py") or name.startswith("_"):
            continue
        names = _read_all_from_stub(resource.read_text(encoding="utf-8"))
        if names:
            result[name] = names
    return result


def _gen_import_statements() -> str:
    """Import statements for _gen/__init__.py using relative form."""
    imports = []
    for file_path, names in _load_file_class_maps().items():
        module_name = os.path.splitext(os.path.basename(file_path))[0]
        imports.append(
            f"""from .{module_name} import (
    {", ".join(names)}
)"""
        )
    return "\n".join(imports) + "\n\n"


def create_import_file_contents() -> str:
    """Return the contents that would be written to _gen/__init__.py."""
    all_names = [n for names in _load_file_class_maps().values() for n in names]
    all_line = "__all__ = [\n    " + ",\n    ".join(f'"{n}"' for n in all_names) + "\n]\n\n"
    return _GEN_FILE_HEADER + all_line + _gen_import_statements()


def _copy_types_tree(pkg: Traversable, dest_dir: str) -> None:
    """Copy the shipped type modules verbatim into *dest_dir*."""
    os.makedirs(dest_dir, exist_ok=True)
    for resource in sorted(pkg.iterdir(), key=lambda r: r.name):
        name = resource.name
        if name == "__pycache__":
            continue
        if resource.is_dir():
            _copy_types_tree(resource, os.path.join(dest_dir, name))
            continue
        if not name.endswith(".py") or (name.startswith("_") and name != "__init__.py"):
            continue
        with open(os.path.join(dest_dir, name), "w", encoding="utf-8") as f:
            f.write(resource.read_text(encoding="utf-8"))


def save_imports(base_path: str) -> None:
    """Save the _gen package: __init__.py and importable stub .py files."""
    gen_dir = os.path.join(base_path, "_gen")
    os.makedirs(gen_dir, exist_ok=True)

    # Remove stale .pyi files left by the interim .pyi-based generation
    for fname in os.listdir(gen_dir):
        if fname.endswith(".pyi"):
            os.remove(os.path.join(gen_dir, fname))

    # Copy type files (including subdirectories) into _gen/
    pkg = importlib.resources.files(_TYPES_PACKAGE)
    _copy_types_tree(pkg, gen_dir)

    # Collect all type names for __all__
    all_names = [n for names in _load_file_class_maps().values() for n in names]

    # Read decorator names from _gen/decorators.py if it was already generated
    decorator_import = ""
    decorators_path = os.path.join(gen_dir, "decorators.py")
    if os.path.isfile(decorators_path):
        with open(decorators_path, encoding="utf-8") as f:
            dec_names = _read_all_from_stub(f.read()) or []
        all_names.extend(dec_names)
        decorator_import = (
            f"from .decorators import {', '.join(dec_names)}\n"
            if dec_names
            else "from .decorators import *\n"
        )

    all_line = "__all__ = [\n    " + ",\n    ".join(f'"{n}"' for n in all_names) + "\n]\n\n"

    with open(os.path.join(gen_dir, "__init__.py"), "w", encoding="utf-8") as f:
        f.write(_GEN_FILE_HEADER + all_line + _gen_import_statements() + decorator_import)
