name: Build Docs

on:
  pull_request:
    paths:
      - 'src/poly/docs/**'
      - '.github/workflows/build-docs.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/poly/docs

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build docs
        run: mkdocs build --strict